# Generated by Django 4.0.4 on 2022-06-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_usersscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersscores',
            name='score',
            field=models.FloatField(),
        ),
    ]
