# Generated by Django 4.0.4 on 2022-06-30 15:15

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_alter_usersscores_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('test_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WordsSimMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(max_length=10000)),
                ('word', models.CharField(max_length=100)),
                ('matrix', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='usersscores',
            old_name='score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='usersscores',
            old_name='words',
            new_name='word',
        ),
        migrations.AddField(
            model_name='usersscores',
            name='item_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='usersscores',
            name='sd',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='usersscores',
            name='timestamp',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='usersscores',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
