# Generated by Django 4.0.4 on 2022-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_usertestresults_wordssimmatrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestresults',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordssimmatrix',
            name='matrix',
            field=models.JSONField(),
        ),
    ]
